<?php

/**
 * @file
 * Primarily Drupal hooks.
 *
 * This is the main module file for Commerce Yandex Market.
 */

/**
 * Implements hook_views_api()
 */
function commerce_yandex_market_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_yandex_market') . '/views',
  );
}

/**
 * Validate callback for "email" field.
 */
function commerce_yandex_market_validate_mail($form, &$form_state) {
  if (!valid_email_address($form_state['values']['style_options']['email'])) {
    form_set_error('style_options][email', t('You must enter a valid e-mail address.'));
  }
}

/**
 * Validate callback for "currencies" field.
 */
function commerce_yandex_market_validate_currencies($form, &$form_state) {
  foreach (explode("\n", trim(($form_state['values']['style_options']['currencies']))) as $line) {
    if (strpos($line, '|') === FALSE) {
      form_set_error('style_options][currencies', t('You must enter a valid currencies.'));
    }
    else {
      list($id, $rate) = explode('|', $line);
      if (empty($id) || empty($rate)) {
        form_set_error('style_options][currencies', t('You must enter a valid currencies.'));
      }
    }
  }
}
